# Generated by Django 2.2 on 2020-12-27 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0002_auto_20201226_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetLikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.TweetModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tweetmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tweet_likes', through='tweets.TweetLikeModel', to=settings.AUTH_USER_MODEL),
        ),
    ]
